version: "3.7"
services:
  web:
    image: nginx:latest
    ports:
    - "80:80"
    - "443:443"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./config/nginx:/etc/nginx/conf.d
      - ./data/logs:/var/log/nginx
      - ./config/cert:/usr/local/nginx/ssl
    links:
      - php7-2
    networks:
        - container_net
  php7-4:
    #image: php:7.2-fpm
    build: './config/php-fpm/7.4'
    tty: true
    volumes:
      - ./www:/usr/share/nginx/html
    networks:
      - container_net
    depends_on:
      - mysql
  php7-2:
    #image: php:7.2-fpm
    build: './config/php-fpm/7.2'
    tty: true
    volumes:
      - ./www:/usr/share/nginx/html
    networks:
      - container_net
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.20
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123.456
    volumes:
      - ./data/database_mysql:/var/www
    networks:
      - container_net
networks:
  container_net:
    external: false