# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./config/nginx:/etc/nginx/conf.d
      - ./data/logs:/var/log/nginx
      - ./config/cert:/usr/local/nginx/ssl
    links:
      - php7-4
    networks:
      - container_net
  php8-1:
    build: './config/php-fpm/8.1'
    expose:
      - "9000"
    tty: true
    volumes:
      - ./www:/usr/share/nginx/html
      - ./config/php-fpm/8.1/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./config/php-fpm/8.1/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - container_net
    environment:
      PHP_IDE_CONFIG: "serverName=freud"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
  php8-4:
    build: './config/php-fpm/8.4'
    expose:
      - "9000"
    tty: true
    volumes:
      - ./www:/usr/share/nginx/html
      - ./config/php-fpm/8.4/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./config/php-fpm/8.4/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - container_net
    environment:
      PHP_IDE_CONFIG: "serverName=php8.4"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
  php7-4:
    build: './config/php-fpm/7.4'
    ports:
      - 9000:9001
    tty: true
    volumes:
      - ./www:/usr/share/nginx/html
      - ./config/php-fpm/7.4/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./config/php-fpm/7.4/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - container_net
    environment:
      PHP_IDE_CONFIG: "serverName=socialhub.co"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.20
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123.456'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123.456'
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - container_net
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123.456
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - container_net
  mongo-express:
    image: mongo-express:0.54
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: username
      ME_CONFIG_BASICAUTH_PASSWORD: 123.456
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123.456
      ME_CONFIG_MONGODB_SERVER: 'mongo'
    links:
      - mongo
    networks:
      - container_net
    depends_on:
      - mongo
  #    restart: unless-stopped
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123.456
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - container_net
  redis:
    container_name: ieducar-redis
    image: redis:alpine
    #    restart: always
    ports:
      - 6379
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.5.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
volumes:
  db_data_mysql:
  db_data_postgres:
  db_data_mongo:
  db_data_elasticsearch:
networks:
  container_net:
    external: true
